all: pa5
pa5: Animal.o ArmyAnt.o ArmyAntQueen.o Bat.o Cat.o Cerberus.o Dog.o Dragon.o Game.o Hawk.o PA5.o Phoenix.o Shark.o Turtle.o
	g++ -o pa5 Animal.o ArmyAnt.o ArmyAntQueen.o Bat.o Cat.o Cerberus.o Dog.o Dragon.o Game.o Hawk.o PA5.o Phoenix.o Shark.o Turtle.o
Animal.o: Animal.h Animal.cpp
	g++ -c Animal.cpp
ArmyAnt.o: ArmyAnt.h ArmyAnt.cpp
	g++ -c ArmyAnt.cpp
ArmyAntQueen.o: ArmyAntQueen.h ArmyAntQueen.cpp
	g++ -c ArmyAntQueen.cpp
Bat.o: Bat.h Bat.cpp
	g++ -c Bat.cpp
Cat.o: Cat.h Cat.cpp
	g++ -c Cat.cpp
Cerberus.o: Cerberus.h Cerberus.cpp
	g++ -c Cerberus.cpp
Dog.o: Dog.h Dog.cpp
	g++ -c Dog.cpp
Dragon.o: Dragon.h Dragon.cpp
	g++ -c Dragon.cpp
Game.o: Game.h Game.cpp
	g++ -c Game.cpp
Hawk.o: Hawk.h Hawk.cpp
	g++ -c Hawk.cpp
PA5.o: PA5.cpp
	g++ -c PA5.cpp
Phoenix.o: Phoenix.h Phoenix.cpp
	g++ -c Phoenix.cpp
Shark.o: Shark.h Shark.cpp
	g++ -c Shark.cpp
Turtle.o: Turtle.h Turtle.cpp
	g++ -c Turtle.cpp
clean:
	rm -f  Animal.o ArmyAnt.o ArmyAntQueen.o Bat.o Cat.o Cerberus.o Dog.o Dragon.o Game.o Hawk.o PA5.o Phoenix.o Shark.o Turtle.o pa5